# Generated by Django 5.0.3 on 2024-03-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('001', 'Banco do Brasil'), ('033', 'Santander'), ('104', 'Caixa'), ('237', 'Bradesco'), ('341', 'Itaú')], max_length=150)),
                ('cnab', models.CharField(default='1', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Cedente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=150)),
                ('cnpj', models.CharField(max_length=14)),
            ],
        ),
    ]
